baseURL                = "https://trees-and-airlines.github.io/"
title                  = "trees-and-airlines"
languageCode           = "en-us"
defaultContentLanguage = "en"
theme                  = "axiom"
# Do not normalize taxonomy(tags) names.
preserveTaxonomyNames  = true
paginate               = 25
canonifyURLs           = false
summaryLength          = 40
rssLimit               = 100
enableEmoji            = true
enableRobotsTXT        = true
pluralizelisttitles    = false

[params]
mainSections      = ["posts"]
copyrightYear     = 2021
# Go Reference time: Mon Jan 2 15:04:05 MST 2006
dateFormat        = "Jan 2, 2006"
highlight         = "dark"
# Max Width Page sections
# maxWidthTitle   = "max-w-2xl"
maxWidthFeature   = "off-max-w-6xl"
# maxWidthContent = "max-w-2xl"
# Max Width Template parts
# maxWidthHeader  = "max-w-6xl"
# maxWidthFooter  = "max-w-6xl"

[params.brand]
domain = "https://trees-and-airlines.github.io/"
email  = "just_trees"

[params.social]
# facebook      = "https://www.facebook.com/user_or_page"
github          = "https://github.com/trees-and-airlines"
# instagram     = "https://instagram.com/user"
# linkedin      = "https://www.linkedin.com/in/user"
# pinterest     = "https://www.pinterest.com/user"
# stackoverflow = "https://stackoverflow.com/users/user"
# twitter       = "https://twitter.com/user"
# youtube       = "https://www.youtube.com/user"
footer          = ["github"]

[params.services]
googleAnalyticsId        = ""
googleTagManagerId       = ""
googleAdsId              = ""
googleAdsenseId          = ""
googleAdsenseAdSlotId    = ""
googleAdsenseLoad        = ""
googleAdsConversionId    = ""
googleAdsConversionValue = 0
facebookApp              = ""
facebookPixel            = ""
disqusShortname          = ""

[params.logo]
# inline = false
# path   = "images/brand/french-press-sm.jpg"
# path   = ""

[params.image]
# width    = "2048"
# height   = "1024"
faviconIco = "favicon/favicon.ico"
faviconAlt = "favicon/favicon.png"
# icon1To1 = "image/brand/icon-1-1.png"
# icon2To1 = "image/brand/icon-2-1.png"
default    = "images/paper.jpg"

[params.font]
type  = ""
path  = ""
files = []

[params.cdn]
provider = "local"
type     = "image"

# [params.cloudinary]
# host    = "https://res.cloudinary.com/CLOUD_NAME/"
# version = ""
# image   = "image/upload/"
# raw     = "raw/upload/"
# video   = "video/upload/"

# [params.cloudinary.presets]
# base    = "f_auto,q_auto/"
# page    = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
# feature = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
# summary = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"

[outputs]
home         = ["HTML", "ATOM"]
section      = ["HTML"]
taxonomy     = ["HTML"]
taxonomyTerm = ["HTML"]

[outputFormats]
[outputFormats.ATOM]
name      = "ATOM"
baseName  = "feed"
mediaType = "application/atom+xml"

[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["atom"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = false
footnote       = true
linkify        = false
strikethrough  = false
table          = true
taskList       = false
typographer    = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
attribute = false

[markup.highlight]
codeFences           = true
noClasses            = false
tabWidth             = 2
# lineNos            = true
# lineNumbersInTable = false

[menu]
[[menu.main]]
url    = "/"
name   = "Home"
weight = 1

[[menu.main]]
url    = "/posts/"
name   = "Posts"
weight = 2

[[menu.main]]
url    = "/about/"
name   = "About"
weight = 3

[[menu.foot]]
url    = "/posts/"
name   = "Posts"
weight = 1

[[menu.foot]]
url    = "/about/"
name   = "About"
weight = 2

[languages]
[languages."en"]
weight       = 1
languageName = "English"
